### ISSUE TITLE
undefined method `sort' for nil:NilClass

### ISSUE THREAD

**Issue by fmh** [rikkipitt/rails_admin_history_rollback#1]
Hello, 
RA : 0.6.7
ROR : 4.2
Great Plugin :+1: 
i get this error when i click on view changes link
![capture d ecran 2015-05-25 a 13 15 23](https://cloud.githubusercontent.com/assets/56861/7796496/303dc4b8-02e0-11e5-9a09-9824872269a9.png)

**Comment by rikkipitt** [comment]
Hi @fmh - thanks for the heads up. I'll take a look and get back to you!

**Comment by rikkipitt** [comment]
Ah, it looks like you didn't install PaperTrail `--with-changes`

You can manually add the extra migrations I believe. They are found [here](https://github.com/airblade/paper_trail/tree/master/lib/generators/paper_trail/templates). Let me know how you get on!

Rikki

**Comment by fmh** [comment]
:+1:  works fine, thx

**Comment by rikkipitt** [comment]
Awesome news! Cheers for confirming and closing the issue.
