### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by aeons** [rikkipitt/rails_admin_history_rollback#11]
With Rails 5 nearing release it would be nice with compatibility for that. :)

**Comment by rikkipitt** [comment]
Thanks for the suggestion @aeons, I've been meaning to release a branch that supports Rails 5 for a while now. RailsAdmin hasn't got a Rails 5 compatible release just yet (although the master does-ish).

Once RailsAdmin has released a new version that supports v5, I'll get something out!

Rikki

**Comment by aeons** [comment]
Sounds good. I'm using the master-ish with a couple of github dependencies forced in to make it work :)

**Comment by rikkipitt** [comment]
Awesome!

I'll probably make this a bit looser on Rails too. It'll support v4 and v5 in their entirety which should help guys such as @martnst with his branch that back "supports" v4.1 in his gemspec.
