### ISSUE TITLE
Missing partial kaminari/ra-twitter-bootstrap/_paginator 

### ISSUE THREAD

**Issue by spbsamuel** [rikkipitt/rails_admin_history_rollback#14]
Faced this issue when using the history feature in rails admin

Showing /Users/samuelphua/.rvm/gems/ruby-2.1.5/gems/rails_admin_history_rollback-0.0.8/app/views/rails_admin/main/history.html.haml where line #56 raised:

Missing partial kaminari/ra-twitter-bootstrap/_paginator with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :haml]}. 

Using kaminari 0.17.0
Using paper_trail 5.2.0
Using rails 4.2.6
Using rails_admin 0.8.1
Using rails_admin_history_rollback 0.0.8

**Comment by rikkipitt** [comment]
Hey @spbsamuel, can you try using v0.0.7 for Rails 4? If that sorts you out I'll update the README!

```
gem "rails_admin_history_rollback", "0.0.7"
```

**Comment by serge1peshcoff** [comment]
I've faced the same issue, for me using v0.0.7 worked.

**Comment by spbsamuel** [comment]
@rikkipitt Sorry for the late reply :S 
How I solved it was to go directly to 
/app/views/rails_admin/main/history.html.haml  
and change kaminari/**ra-twitter-bootstrap**/_paginator to kaminari/**twitter-bootstrap**/_paginator

Didn't have to use v0.0.7. The main rails admin project changed from twitter-bootstrap to ra-twitter-bootstrap for some name spacing reason.

**Comment by serge1peshcoff** [comment]
@spbsamuel yeah, though it seems like this renaming will be presented in `rails_admin` v1.0, and the current `rails_admin` version (0.8.1). still refers to `kaminari/twitter-bootstrap/_paginator`.

**Comment by rikkipitt** [comment]
Tricky! I'll take a more in depth look today if I get chance and try and support both versions.

**Comment by spbsamuel** [comment]
@serge1peshcoff @rikkipitt  Thanks for help

**Comment by spbsamuel** [comment]
@rikkipitt @serge1peshcoff Thanks for your help!

https://github.com/sferik/rails_admin/issues/2283 You can refer to this issue for details why it was changed to ra-twitter-bootstrap
