### ISSUE TITLE
Crashes when reverting a model linked to not existing child model

### ISSUE THREAD

**Issue by serge1peshcoff** [rikkipitt/rails_admin_history_rollback#15]
Related: https://github.com/airblade/paper_trail/issues/841

How to reproduce: 
1) I have Stadium and StadiumUser models, and the dependency between them is like that:

```
class StadiumUser < User
    ....
    has_one :stadium, foreign_key: "user_id", dependent: :destroy, required: true
    after_create :make_stadium
end
```

2) I created the StadiumUser (Stadium is created with it)
3) I deleted StadiumUser via rails_admin
4) I find the Stadium deletion entry and press "Restore"
5) this error appears

```
PG::ForeignKeyViolation at /stadium/history
ERROR:  insert or update on table "stadiums" violates foreign key constraint "fk_rails_b1bd5d1cc5"
DETAIL:  Key (user_id)=(56) is not present in table "users". 
```

**Comment by rikkipitt** [comment]
Hi @serge1peshcoff does this help?

https://github.com/airblade/paper_trail#4b-associations

Related issue on this repo: #5 

Rikki

**Comment by serge1peshcoff** [comment]
I can't check it for now, but it shouldn't work either, since no `has_one: true` param is specified when using paper_trail's `reify`.
Anyway, will check it out later.
