### ISSUE TITLE
Rollback for create action

### ISSUE THREAD

**Issue by fmh** [rikkipitt/rails_admin_history_rollback#2]
Hello again,
I have this new error when I try a rollback for a create action
![capture d ecran 2015-05-26 a 23 40 37](https://cloud.githubusercontent.com/assets/56861/7824115/c86e00ec-0400-11e5-8755-bfad3a2b6175.png)

maybe some improvements are needed : 
rollback "create record A" => delete record A, actually error
rollback "update record A , attribute name" => rollback "update record A attribute name with last value" , actually clone record A, attribute name with last value

**Comment by rikkipitt** [comment]
Hmm, strange. I'll look into it!

**Comment by fmh** [comment]
thx :)

**Comment by fmh** [comment]
enhancement:
add support to restore associations (has_many , has_many_thorugh, has_one), i'll check this to help to improve this plugin

**Comment by rikkipitt** [comment]
Cheers @fmh - that would be a great addition to the project! Thanks for you help!

Rikki

**Comment by rikkipitt** [comment]
Hi @fmh, I've just installed my plugin on the latest rails_admin. I created a record then rolled back. This gives a "destroy" event perfectly... If I rollback the destroyed record, it gets restored as expected.

I'll continue some testing to see what's up!

Rikki

**Comment by fmh** [comment]
It works for me now, it was a problem with my versions tables  :( 
thx a lot

**Comment by rikkipitt** [comment]
Thanks for confirming! Hope it's all working as expected.
