### ISSUE TITLE
Chinese is a default I18n ?

### ISSUE THREAD

**Issue by fmh** [rikkipitt/rails_admin_history_rollback#3]
my history table is with Chinese by default and change to EN has no effect.

![capture d ecran 2015-06-21 a 18 49 42](https://cloud.githubusercontent.com/assets/56861/8272539/9c3c361a-1846-11e5-92e8-0ba7b1f58fac.png)

**Comment by rikkipitt** [comment]
Interesting! I added I18n the other day as some of the copy was hard-coded... let me look into this for you. It's okay on my system. What's your default language?

Riki

**Comment by fmh** [comment]
EN is my default language

**Comment by rikkipitt** [comment]
Have you restarted your server? I'm using v0.0.4 on my local machine and it's okay...

**Comment by fmh** [comment]
I'm also using 0.0.4 and I'm in developement

**Comment by rikkipitt** [comment]
Hmm, perhaps I've got the naming convention wrong on the locales files?

**Comment by fmh** [comment]
Yes you have two :en in locales files

**Comment by rikkipitt** [comment]
Good spot! Schoolboy error, fixing it now.

**Comment by fmh** [comment]
thx :+1:

**Comment by rikkipitt** [comment]
If you bundle update this gem, that should fix your problem! Sorry about that! Let me know if it helps.

**Comment by fmh** [comment]
good job, thx
