### ISSUE TITLE
The asset "rails_admin/ra.history.css" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by KellyBennett** [rikkipitt/rails_admin_history_rollback#31]
Hello,

I'm trying to use this awesome gem with 

- ruby 3.0.6
- rails 7.0.7.2
- rails_admin 3.1.2
- paper_trail 15.0.0

When I run the rails_admin portal locally everything works as expected. However if I run in "production" mode, with `config.assets.debug = false`, The admin_portal displays and error.

![image](https://github.com/jemcode/rails_admin_history_rollback/assets/4806426/912e3b3c-32e7-4b07-8790-e8f30261dcaa)

And in sentry I see the error
`The asset "rails_admin/ra.history.css" is not present in the asset pipeline.`

I'm not super familiar with the rails asset pipeline. Happy to supply more information if it's helpful! 

Thanks!

**Comment by KellyBennett** [comment]
I solved this by adding `rails_admin/ra.history.css` to my precompile list in `config/initializers/assets`

```
Rails.application.config.assets.precompile += [
  'rails_admin/ra.history.css',
  'rails_admin/application.css',
  'rails_admin/application.js',
]
```

**Comment by rikkipitt** [comment]
@KellyBennett Super! Glad you figure out the solution. Sorry I didn't get to you earlier, but appreciate your perseverance. Thanks for closing out the issue too!
